import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import * as Popover from '@radix-ui/react-popover';
import * as Select from '@radix-ui/react-select';
import * as Collapsible from '@radix-ui/react-collapsible';
import * as RadioGroup from '@radix-ui/react-radio-group';
import * as AlertDialog from '@radix-ui/react-alert-dialog';
import { App as NativeApp } from '@capacitor/app';
import { DayPicker } from 'react-day-picker';
import { CartesianGrid, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import {
  Archive, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Circle,
  Clock3, Columns3, Folder, Grid2X2, Inbox, List, ListTodo, Plus,
  Pencil, RefreshCw, Search, SlidersHorizontal, Tag, X
} from 'lucide-react';
import './styles.css';
import './mobile.css';
import './mobile-features.css';
import './mobile-manager.css';
import './multica-style.css';

const config = window.TODO_CONFIG || {};
const API_ROOT = (config.supabaseUrl || '').replace(/\/$/, '').includes('/rest/v1')
  ? `${(config.supabaseUrl || '').replace(/\/$/, '')}/`
  : `${(config.supabaseUrl || '').replace(/\/$/, '')}/rest/v1/`;
const STATUS_COLUMNS = [
  { key: '收件箱', label: '待规划', tone: 'plan' },
  { key: '待进行', label: '待办', tone: 'todo' },
  { key: '进行中', label: '进行中', tone: 'doing' },
  { key: '已完成', label: '已完成', tone: 'done' },
  { key: '阻塞', label: '已阻塞', tone: 'blocked' },
  { key: '已取消', label: '已取消', tone: 'cancelled' }
];
const STATUS_OPTIONS = STATUS_COLUMNS.map((item) => item.key);
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai' }).format(new Date());
const dateOnly = (value) => {
  if (!value) return '';
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai' }).format(new Date(value));
};
const localDateTimeValue = (value) => {
  if (!value) return '';
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(value)).reduce((result, part) => ({ ...result, [part.type]: part.value }), {});
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;
};
const active = (task) => !task.archived_at && !['已完成', '已取消'].includes(task.status);
const displayStatus = (status) => STATUS_COLUMNS.find((item) => item.key === status)?.label || status;

async function api(path, options = {}) {
  if (!config.supabaseUrl || !config.supabaseAnonKey) throw new Error('尚未配置 Supabase 连接信息');
  const response = await fetch(`${API_ROOT}${path}`, {
    ...options,
    headers: { apikey: config.supabaseAnonKey, 'Content-Type': 'application/json', ...(options.headers || {}) }
  });
  if (!response.ok) throw new Error((await response.text()) || '请求失败');
  const text = await response.text();
  return text ? JSON.parse(text) : null;
}

function App() {
  const [tasks, setTasks] = useState([]);
  const [projects, setProjects] = useState([]);
  const [categories, setCategories] = useState([]);
  const [view, setView] = useState('today');
  const [viewMode, setViewMode] = useState('board');
  const [selected, setSelected] = useState(null);
  const [projectFilter, setProjectFilter] = useState(null);
  const [search, setSearch] = useState('');
  const [month, setMonth] = useState(() => new Date());
  const [filters, setFilters] = useState({ status: '', priority: '', date: '', project: '', category: '' });
  const [filterOpen, setFilterOpen] = useState(false);
  const [quickCreate, setQuickCreate] = useState(false);
  const [quickStatus, setQuickStatus] = useState('收件箱');
  const [quickParent, setQuickParent] = useState(null);
  const [addingProject, setAddingProject] = useState(false);
  const [addingCategory, setAddingCategory] = useState(false);
  const [editingProject, setEditingProject] = useState(null);
  const [editingCategory, setEditingCategory] = useState(null);
  const [notice, setNotice] = useState('');
  const [undoAction, setUndoAction] = useState(null);
  const [mobileMore, setMobileMore] = useState(false);
  const [loading, setLoading] = useState(true);
  const [isMobile, setIsMobile] = useState(() => window.matchMedia('(max-width: 720px)').matches);

  const flash = (message, undo = null) => {
    setNotice(message);
    setUndoAction(() => undo);
    window.clearTimeout(window.__todoNoticeTimer);
    window.__todoNoticeTimer = window.setTimeout(() => { setNotice(''); setUndoAction(null); }, 5000);
  };

  const load = async () => {
    setLoading(true);
    try {
      const [nextTasks, nextProjects, nextCategories] = await Promise.all([
        api('tasks?user_id=is.null&select=*&order=manual_order.desc,created_at.desc'),
        api('projects?user_id=is.null&select=*&order=created_at.asc'),
        api('categories?user_id=is.null&select=*&order=created_at.asc')
      ]);
      setTasks(nextTasks || []); setProjects(nextProjects || []); setCategories(nextCategories || []);
      setSelected((current) => current ? (nextTasks || []).find((item) => item.id === current.id) || null : null);
    } catch (error) { flash(error.message || '加载失败，请稍后重试'); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  useEffect(() => {
    const media = window.matchMedia('(max-width: 720px)');
    const sync = () => setIsMobile(media.matches);
    media.addEventListener('change', sync);
    return () => media.removeEventListener('change', sync);
  }, []);

  const childrenByParent = useMemo(() => {
    const map = new Map();
    tasks.forEach((task) => { if (task.parent_id) map.set(task.parent_id, [...(map.get(task.parent_id) || []), task]); });
    return map;
  }, [tasks]);

  const visibleTasks = useMemo(() => tasks.filter((task) => {
    if (task.parent_id || (projectFilter && task.project_id !== projectFilter)) return false;
    if (filters.status && task.status !== filters.status) return false;
    if (filters.project && task.project_id !== filters.project) return false;
    if (filters.category && task.category_id !== filters.category) return false;
    if (filters.priority === 'important' && !task.importance) return false;
    if (filters.priority === 'urgent' && !task.urgency) return false;
    if (filters.date === 'overdue' && !(task.due_at && dateOnly(task.due_at) < today())) return false;
    if (filters.date === 'today' && dateOnly(task.due_at) !== today() && task.scheduled_for !== today()) return false;
    const term = search.trim().toLocaleLowerCase();
    if (!term) return true;
    const project = projects.find((item) => item.id === task.project_id)?.name || '';
    const category = categories.find((item) => item.id === task.category_id)?.name || '';
    return [task.title, task.description, project, category].join(' ').toLocaleLowerCase().includes(term);
  }), [tasks, projectFilter, filters, search, projects, categories]);

  const updateTask = async (id, patch, message = '已保存') => {
    try {
      const result = await api(`tasks?id=eq.${id}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify(patch) });
      const updated = result?.[0];
      if (updated) { setTasks((items) => items.map((item) => item.id === id ? updated : item)); setSelected((item) => item?.id === id ? updated : item); }
      if (message) flash(message);
      return updated;
    } catch (error) { flash(error.message || '保存失败'); return null; }
  };
  const deleteTask = async (task) => {
    try {
      await api(`tasks?id=eq.${task.id}`, { method: 'DELETE' });
      const descendants = new Set([task.id]); let changed = true;
      while (changed) { changed = false; tasks.forEach((item) => { if (item.parent_id && descendants.has(item.parent_id) && !descendants.has(item.id)) { descendants.add(item.id); changed = true; } }); }
      setTasks((items) => items.filter((item) => !descendants.has(item.id)));
      setSelected((current) => current?.id === task.id ? null : current);
      flash('任务已删除');
      return true;
    } catch (error) { flash(error.message || '删除失败'); return false; }
  };
  const createTask = async ({ title, description = '', projectId = projectFilter, categoryId = null, parentId = null, status = '收件箱', importance = false, urgency = false, scheduledFor = null, dueAt = null }) => {
    const trimmed = title.trim(); if (!trimmed) return null;
    try {
      const result = await api('tasks', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ title: trimmed, description: description.trim(), status, project_id: projectId || null, category_id: categoryId || null, parent_id: parentId, importance, urgency, scheduled_for: scheduledFor || null, due_at: dueAt ? new Date(`${dueAt}:00+08:00`).toISOString() : null, manual_order: Date.now() }) });
      const task = result?.[0]; if (task) setTasks((items) => [task, ...items]);
      flash(parentId ? '子任务已创建' : projectId ? '已加入当前项目' : '已加入收件箱');
      return task;
    } catch (error) { flash(error.message || '创建失败，请重试'); return null; }
  };
  const createProject = async (name) => {
    if (!name.trim()) return false;
    try { const data = await api('projects', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ name: name.trim(), color: '#5f7eea' }) }); setProjects((items) => [...items, data[0]]); flash('项目已创建'); return true; }
    catch (error) { flash(error.message || '创建项目失败'); return false; }
  };
  const createCategory = async (name, projectId) => {
    if (!name.trim() || !projectId) return false;
    try { const data = await api('categories', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ name: name.trim(), project_id: projectId }) }); setCategories((items) => [...items, data[0]]); flash('分类已创建'); return true; }
    catch (error) { flash(error.message || '创建分类失败'); return false; }
  };
  const renameProject = async (id, name) => { if (!name.trim()) return false; try { const data = await api(`projects?id=eq.${id}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ name: name.trim() }) }); if (data?.[0]) setProjects((items) => items.map((item) => item.id === id ? data[0] : item)); flash('项目已重命名'); return true; } catch (error) { flash(error.message || '重命名失败'); return false; } };
  const renameCategory = async (id, name) => { if (!name.trim()) return false; try { const data = await api(`categories?id=eq.${id}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ name: name.trim() }) }); if (data?.[0]) setCategories((items) => items.map((item) => item.id === id ? data[0] : item)); flash('分类已重命名'); return true; } catch (error) { flash(error.message || '重命名失败'); return false; } };
  const completeTask = async (task) => { const nextStatus = task.status === '已完成' ? '待进行' : '已完成'; const updated = await updateTask(task.id, { status: nextStatus }, ''); if (updated) flash(nextStatus === '已完成' ? '任务已完成' : '任务已恢复', () => updateTask(task.id, { status: task.status }, '已撤销')); };
  const changeView = (next) => { setView(next); setProjectFilter(null); setSearch(''); setQuickCreate(false); setQuickParent(null); setMobileMore(false); };
  const clearFilters = () => setFilters({ status: '', priority: '', date: '', project: '', category: '' });
  const hasFilters = Object.values(filters).some(Boolean) || Boolean(projectFilter);
  const titleMap = { inbox: '收件箱', today: '行动', status: '任务', quadrant: '四象限', calendar: '日历', archive: '归档', review: '本周回顾', project: '项目任务' };
  const title = projectFilter ? projects.find((item) => item.id === projectFilter)?.name || '项目' : titleMap[view];
  const subtitle = projectFilter ? '任务按状态组织，支持切换看板或列表浏览' : { status: '以状态为线索，快速掌握全部任务', inbox: '快速收集、集中处理，保持主工作区清爽', today: '先完成最重要、最需要行动的事', quadrant: '一掐四：用位置判断轻重缓急', calendar: '按计划与截止日期查看任务', archive: '已完成、取消或归档的记录', review: '自动汇总本周的完成与待处理事项' }[view];
  useEffect(() => {
    if (isMobile || !window.Capacitor?.isNativePlatform?.()) return undefined;
    let listener;
    NativeApp.addListener('backButton', () => {
      if (selected) return setSelected(null);
      if (quickCreate) { setQuickCreate(false); return setQuickParent(null); }
      if (mobileMore) return setMobileMore(false);
      if (view !== 'today' || projectFilter) return changeView('today');
      NativeApp.exitApp();
    }).then((handle) => { listener = handle; });
    return () => listener?.remove();
  }, [isMobile, selected, quickCreate, mobileMore, view, projectFilter]);

  return <><MobileApp tasks={tasks} projects={projects} categories={categories} childrenByParent={childrenByParent} loading={loading} onCreate={createTask} onSave={updateTask} onDelete={deleteTask} onComplete={completeTask} onCreateProject={createProject} onCreateCategory={createCategory} onRenameProject={renameProject} onRenameCategory={renameCategory} /><div className="shell desktop-shell">
    <aside className="sidebar">
      <div className="brand"><b><ListTodo size={16} strokeWidth={2.5} /></b><span>任务</span></div>
      <button className="primary sidebar-create" onClick={() => { setQuickStatus('收件箱'); setQuickCreate(true); }}><Plus size={16} />新建任务</button>
      <nav className="nav" aria-label="主导航">
        <NavButton icon={Inbox} label="收件箱" active={!projectFilter && view === 'inbox'} onClick={() => changeView('inbox')} count={tasks.filter((item) => active(item) && item.status === '收件箱' && !item.parent_id).length} />
        <NavButton icon={Columns3} label="状态视图" active={!projectFilter && view === 'status'} onClick={() => changeView('status')} />
        <NavButton icon={Clock3} label="行动" active={!projectFilter && view === 'today'} onClick={() => changeView('today')} />
        <NavButton icon={Grid2X2} label="四象限" active={!projectFilter && view === 'quadrant'} onClick={() => changeView('quadrant')} />
        <NavButton icon={CalendarDays} label="日历" active={!projectFilter && view === 'calendar'} onClick={() => changeView('calendar')} />
        <NavButton icon={Archive} label="归档" active={!projectFilter && view === 'archive'} onClick={() => changeView('archive')} />
        <NavButton icon={Clock3} label="本周回顾" active={!projectFilter && view === 'review'} onClick={() => changeView('review')} />
      </nav>
      <div className="side-heading"><span>项目与分类</span><button aria-label="新建节点" onClick={() => setAddingProject(true)}><Plus size={15} /></button></div>
      <div className="project-tree">
        {projects.map((project) => <div className="tree-project" key={project.id}>{editingProject === project.id ? <InlineRename initialValue={project.name} onCancel={() => setEditingProject(null)} onSubmit={async (name) => { if (await renameProject(project.id, name)) setEditingProject(null); }} /> : <div className="tree-node-action"><button className={projectFilter === project.id ? 'project active' : 'project'} onClick={() => { setProjectFilter(project.id); setView('project'); setQuickCreate(false); }}><i style={{ background: project.color || '#5f7eea' }} /><span>{project.name}</span></button><button className="tree-edit" aria-label={`重命名项目 ${project.name}`} onClick={() => setEditingProject(project.id)}><Pencil size={12} /></button></div>}{categories.filter((category) => category.project_id === project.id).map((category) => editingCategory === category.id ? <InlineRename key={category.id} initialValue={category.name} onCancel={() => setEditingCategory(null)} onSubmit={async (name) => { if (await renameCategory(category.id, name)) setEditingCategory(null); }} /> : <div className="tree-node-action category-node" key={category.id}><button className="tree-category" onClick={() => { setProjectFilter(project.id); setFilters((current) => ({ ...current, category: category.id })); setView('project'); }}><Tag size={12} />{category.name}</button><button className="tree-edit" aria-label={`重命名分类 ${category.name}`} onClick={() => setEditingCategory(category.id)}><Pencil size={12} /></button></div>)}<button className="tree-add-category" onClick={() => { setProjectFilter(project.id); setAddingCategory(true); }}><Plus size={12} />新增分类</button></div>)}
        {addingProject && <InlineName placeholder="项目名称，按回车键创建" onCancel={() => setAddingProject(false)} onSubmit={async (name) => { if (await createProject(name)) setAddingProject(false); }} />}
        {!projects.length && !addingProject && <p>还没有项目</p>}
      </div>
      {addingCategory && <div className="category-tree"><InlineCategory projects={projects} projectId={projectFilter} onCancel={() => setAddingCategory(false)} onSubmit={async (name, projectId) => { if (await createCategory(name, projectId)) setAddingCategory(false); }} /></div>}
    </aside>

    <main className={view === 'inbox' && !projectFilter ? 'main inbox-main' : 'main'}>
      <header className={(view === 'status' || view === 'project') ? 'topbar task-topbar' : 'topbar'}>
        <div><h1>{title}</h1><p>{subtitle}</p></div>
        <div className="toolbar task-toolbar">
          <label className="search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索任务" /></label>
          <div className="filter-wrap"><button className={hasFilters ? 'toolbar-button active-filter' : 'toolbar-button'} onClick={() => setFilterOpen((open) => !open)}><SlidersHorizontal size={15} />筛选</button>{filterOpen && <FilterMenu filters={filters} setFilters={setFilters} projects={projects} categories={categories} onClear={clearFilters} onClose={() => setFilterOpen(false)} />}</div>
          {(view === 'status' || view === 'project') && <ViewSwitch mode={viewMode} setMode={setViewMode} />}
          {(view === 'status' || view === 'project') && <button className="primary task-create" onClick={() => { setQuickParent(null); setQuickStatus('待进行'); setQuickCreate(true); }}><Plus size={15} />新建任务</button>}
          <button className="icon-button" title="刷新数据" onClick={load}><RefreshCw size={16} /></button>
        </div>
      </header>
      <CreateTaskSheet open={quickCreate} initialStatus={quickStatus} projectId={projectFilter} parentTask={quickParent} projects={projects} categories={categories} onOpenChange={(open) => { setQuickCreate(open); if (!open) setQuickParent(null); }} onSubmit={(payload) => createTask(payload)} />
      {hasFilters && <div className="filter-bar filter-summary"><strong>当前筛选</strong>{projectFilter && <span>项目 · {projects.find((item) => item.id === projectFilter)?.name}</span>}{filters.status && <span>状态 · {displayStatus(filters.status)}</span>}{filters.priority && <span>优先级 · {filters.priority === 'important' ? '重要' : '紧急'}</span>}{filters.date && <span>日期 · {filters.date === 'today' ? '今天' : '已逾期'}</span>}{filters.project && <span>项目 · {projects.find((item) => item.id === filters.project)?.name}</span>}{filters.category && <span>分类 · {categories.find((item) => item.id === filters.category)?.name}</span>}<button onClick={() => { clearFilters(); setProjectFilter(null); }}>清除全部</button></div>}
      <section className="content" aria-busy={loading}>
        {loading ? <div className="empty">正在载入任务…</div> : <ViewContent view={projectFilter ? 'project' : view} mode={viewMode} tasks={visibleTasks} month={month} setMonth={setMonth} onSelect={setSelected} onComplete={completeTask} onUpdate={updateTask} onDelete={deleteTask} onCreate={createTask} childrenByParent={childrenByParent} projects={projects} categories={categories} onQuickCreate={(status, parentTask = null) => { setQuickStatus(status); setQuickParent(parentTask); setQuickCreate(true); }} />}
      </section>
    </main>

    <TaskSheet task={selected} projects={projects} categories={categories} childTasks={selected ? childrenByParent.get(selected.id) || [] : []} onClose={() => setSelected(null)} onSave={updateTask} onDelete={deleteTask} onOpenTask={setSelected} onAddChild={() => selected && (() => { setQuickParent(selected); setQuickStatus('待进行'); setQuickCreate(true); })()} />
    <nav className="mobile-nav" aria-label="移动导航"><button className={!projectFilter && view === 'inbox' ? 'active' : ''} onClick={() => changeView('inbox')}><Inbox size={18} /><span>收件箱</span></button><button className={!projectFilter && view === 'status' ? 'active' : ''} onClick={() => changeView('status')}><ListTodo size={18} /><span>任务</span></button><button className="mobile-add" onClick={() => { setQuickParent(null); setQuickStatus('收件箱'); setQuickCreate(true); }} aria-label="新建任务"><Plus size={22} /></button><button className={!projectFilter && view === 'today' ? 'active' : ''} onClick={() => changeView('today')}><Clock3 size={18} /><span>行动</span></button><button onClick={() => setMobileMore((open) => !open)} aria-expanded={mobileMore}><SlidersHorizontal size={18} /><span>更多</span></button></nav>{mobileMore && <div className="mobile-more-menu mobile-more-menu-fixed"><button onClick={() => { changeView('calendar'); setMobileMore(false); }}><CalendarDays size={16} />日历</button><button onClick={() => { changeView('quadrant'); setMobileMore(false); }}><Grid2X2 size={16} />四象限</button><button onClick={() => { changeView('review'); setMobileMore(false); }}><Clock3 size={16} />本周回顾</button><button onClick={() => { changeView('archive'); setMobileMore(false); }}><Archive size={16} />归档</button></div>}
    {notice && <div className="notice" role="status"><span>{notice}</span>{undoAction && <button onClick={() => { undoAction(); setNotice(''); setUndoAction(null); }}>撤销</button>}</div>}
  </div></>;
}

function MobileApp({ tasks, projects, categories, childrenByParent, loading, onCreate, onSave, onDelete, onComplete, onCreateProject, onCreateCategory, onRenameProject, onRenameCategory }) {
  const [tab, setTab] = useState('action');
  const [screenStack, setScreenStack] = useState([]);
  const screen = screenStack[screenStack.length - 1] || null;
  const activeTasks = tasks.filter((task) => active(task) && !task.parent_id);
  const openDetail = (task) => setScreenStack((items) => [...items, { type: 'detail', taskId: task.id }]);
  const openCreate = (parentTask = null) => setScreenStack((items) => [...items, { type: 'create', parentTask }]);
  const closeScreen = () => setScreenStack((items) => items.slice(0, -1));

  useEffect(() => {
    if (!window.Capacitor?.isNativePlatform?.()) return undefined;
    let listener;
    NativeApp.addListener('backButton', () => {
      if (screen) return closeScreen();
      if (tab !== 'action') return setTab('action');
      NativeApp.exitApp();
    }).then((handle) => { listener = handle; });
    return () => listener?.remove();
  }, [screen, tab]);

  const selectedTask = screen?.type === 'detail' ? tasks.find((item) => item.id === screen.taskId) : null;
  return <div className="mobile-app">
    {!screen && <><header className="mobile-app-head"><div><span className="mobile-kicker">任务</span><h1>{tab === 'action' ? '现在要做什么？' : tab === 'inbox' ? '收集箱' : '浏览任务'}</h1></div><button className="mobile-create-icon" onClick={() => openCreate()} aria-label="新建任务"><Plus size={21} /></button></header>
      <main className="mobile-app-content">{loading ? <div className="mobile-empty">正在载入任务…</div> : tab === 'action' ? <MobileAction tasks={activeTasks} projects={projects} onOpen={openDetail} onComplete={onComplete} onCreate={openCreate} /> : tab === 'inbox' ? <MobileInbox tasks={activeTasks.filter((task) => task.status === '收件箱')} projects={projects} onOpen={openDetail} onComplete={onComplete} onCreate={openCreate} /> : <MobileBrowse tasks={tasks.filter((task) => !task.parent_id)} projects={projects} categories={categories} childrenByParent={childrenByParent} onOpen={openDetail} onComplete={onComplete} onCreateProject={onCreateProject} onCreateCategory={onCreateCategory} onRenameProject={onRenameProject} onRenameCategory={onRenameCategory} />}</main>
      <nav className="mobile-tabbar" aria-label="移动主导航"><button className={tab === 'action' ? 'active' : ''} onClick={() => setTab('action')}><Clock3 size={20} /><span>行动</span></button><button className={tab === 'inbox' ? 'active' : ''} onClick={() => setTab('inbox')}><Inbox size={20} /><span>收集</span></button><button className="mobile-tab-add" onClick={() => openCreate()} aria-label="记录任务"><Plus size={23} /></button><button className={tab === 'browse' ? 'active' : ''} onClick={() => setTab('browse')}><ListTodo size={20} /><span>浏览</span></button></nav>
    </>}
    {screen?.type === 'create' && <MobileTaskForm parentTask={screen.parentTask} projects={projects} categories={categories} onBack={closeScreen} onCreate={async (payload) => { const created = await onCreate(payload); if (created) setScreenStack((items) => [...items.slice(0, -1), { type: 'detail', taskId: created.id }]); }} />}
    {selectedTask && <MobileTaskDetail task={selectedTask} projects={projects} categories={categories} childTasks={childrenByParent.get(selectedTask.id) || []} onBack={closeScreen} onSave={onSave} onComplete={onComplete} onDelete={async (task) => { if (window.confirm(`删除“${task.title}”及其子任务？`)) { const deleted = await onDelete(task); if (deleted) closeScreen(); } }} onOpen={openDetail} onAddChild={() => openCreate(selectedTask)} />}
  </div>;
}

function MobileAction({ tasks, projects, onOpen, onComplete, onCreate }) {
  const todayTasks = tasks.filter((task) => task.scheduled_for === today() || dateOnly(task.due_at) === today());
  const focus = tasks.filter((task) => task.importance || task.urgency).sort((a, b) => Number(b.importance) + Number(b.urgency) - Number(a.importance) - Number(a.urgency));
  const remainder = tasks.filter((task) => !focus.some((item) => item.id === task.id) && !todayTasks.some((item) => item.id === task.id));
  return <div className="mobile-action"><p className="mobile-date">{new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date())}</p><button className="mobile-capture" onClick={() => onCreate()}><Plus size={19} /><span>记录一件要做的事</span><small>稍后再整理</small></button><MobileTaskSection title="优先处理" hint="重要或紧急" tasks={focus} projects={projects} onOpen={onOpen} onComplete={onComplete} /><MobileTaskSection title="今天计划" hint={`${todayTasks.length} 项`} tasks={todayTasks} projects={projects} onOpen={onOpen} onComplete={onComplete} /><MobileTaskSection title="其他待处理" hint={`${remainder.length} 项`} tasks={remainder.slice(0, 6)} projects={projects} onOpen={onOpen} onComplete={onComplete} empty="暂时没有其他待处理任务" /></div>;
}

function MobileInbox({ tasks, projects, onOpen, onComplete, onCreate }) { return <div className="mobile-inbox"><p className="mobile-intro">先收集，之后再决定项目、时间和优先级。</p><button className="mobile-capture" onClick={() => onCreate()}><Plus size={19} /><span>收集一条任务</span><small>{tasks.length} 条待处理</small></button>{tasks.length ? <div className="mobile-list">{tasks.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} onComplete={onComplete} />)}</div> : <div className="mobile-empty"><Inbox size={28} /><strong>收集箱已经清空</strong><span>把突然想到的事情先记在这里。</span></div>}</div>; }

function MobileBrowse({ tasks, projects, categories, childrenByParent, onOpen, onComplete, onCreateProject, onCreateCategory, onRenameProject, onRenameCategory }) {
  const [mode, setMode] = useState('status'); const [toolsOpen, setToolsOpen] = useState(false); const [query, setQuery] = useState(''); const [filterOpen, setFilterOpen] = useState(false); const [filter, setFilter] = useState({ priority: '', status: '', project: '', category: '' });
  const filtered = tasks.filter((task) => { const haystack = [task.title, task.description, projects.find((item) => item.id === task.project_id)?.name, categories.find((item) => item.id === task.category_id)?.name].join(' ').toLowerCase(); if (query && !haystack.includes(query.toLowerCase())) return false; if (filter.status && task.status !== filter.status) return false; if (filter.project && task.project_id !== filter.project) return false; if (filter.category && task.category_id !== filter.category) return false; if (filter.priority === 'important' && !task.importance) return false; if (filter.priority === 'urgent' && !task.urgency) return false; return true; });
  const activeTasks = filtered.filter(active); const archivedTasks = filtered.filter((task) => !active(task));
  const groups = mode === 'status' ? STATUS_COLUMNS.map((column) => ({ key: column.key, name: column.label, tasks: activeTasks.filter((task) => task.status === column.key) })) : projects.map((project) => ({ key: project.id, name: project.name, color: project.color, tasks: activeTasks.filter((task) => task.project_id === project.id) }));
  const toolTitle = { calendar: '日历', quadrant: '四象限', review: '本周回顾', archive: '归档', manage: '项目与分类' }[mode];
  const chooseTool = (next) => { setMode(next); setToolsOpen(false); setFilterOpen(false); };
  return <div className="mobile-browse"><div className="mobile-workspace-head"><div className="mobile-view-switch"><button className={mode === 'status' ? 'selected' : ''} onClick={() => { setMode('status'); setToolsOpen(false); }}>状态</button><button className={mode === 'project' ? 'selected' : ''} onClick={() => { setMode('project'); setToolsOpen(false); }}>项目</button></div><button className={toolsOpen || toolTitle ? 'mobile-tools active' : 'mobile-tools'} onClick={() => setToolsOpen((open) => !open)}>{toolTitle || '工具'}<ChevronDown size={15} /></button></div>{toolsOpen ? <MobileExploreHub onChoose={chooseTool} /> : <>{toolTitle && <div className="mobile-tool-title"><button onClick={() => setMode('status')}><ChevronLeft size={16} />返回任务</button><strong>{toolTitle}</strong></div>}{mode !== 'manage' && !toolTitle && <><div className="mobile-search-row"><label><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索任务" /></label><button className={filterOpen ? 'selected' : ''} onClick={() => setFilterOpen((open) => !open)}><SlidersHorizontal size={16} />筛选</button></div>{filterOpen && <MobileFilters filter={filter} setFilter={setFilter} projects={projects} categories={categories} />}</>}{mode === 'manage' ? <MobileProjectManager projects={projects} categories={categories} onCreateProject={onCreateProject} onCreateCategory={onCreateCategory} onRenameProject={onRenameProject} onRenameCategory={onRenameCategory} /> : mode === 'calendar' ? <MobileCalendar tasks={activeTasks} projects={projects} onOpen={onOpen} /> : mode === 'quadrant' ? <MobileQuadrants tasks={activeTasks} projects={projects} childrenByParent={childrenByParent} onOpen={onOpen} /> : mode === 'review' ? <MobileReview tasks={tasks} projects={projects} onOpen={onOpen} /> : mode === 'archive' ? <MobileArchive tasks={archivedTasks} projects={projects} onOpen={onOpen} onComplete={onComplete} /> : mode === 'status' ? <MobileStatusBoard groups={groups} projects={projects} onOpen={onOpen} onComplete={onComplete} /> : groups.map((group) => <section className="mobile-group" key={group.key}><header>{group.color && <i style={{ background: group.color }} />}<strong>{group.name}</strong><small>{group.tasks.length}</small></header>{group.tasks.length ? group.tasks.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} onComplete={onComplete} />) : <p>暂无任务</p>}</section>)}</>}</div>;
}
function MobileStatusBoard({ groups, projects, onOpen, onComplete }) { return <section className="mobile-status-board">{groups.map((group) => <article className="mobile-board-column" key={group.key}><header><span className={`status-dot ${group.key === '进行中' ? 'tone-doing' : group.key === '已完成' ? 'tone-done' : group.key === '阻塞' ? 'tone-blocked' : ''}`} /><strong>{group.name}</strong><small>{group.tasks.length}</small></header><div>{group.tasks.length ? group.tasks.map((task) => <MobileBoardCard key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} onComplete={onComplete} />) : <p>暂无任务</p>}</div></article>)}</section>; }
function MobileBoardCard({ task, project, onOpen, onComplete }) { const due = dateOnly(task.due_at); return <article className="mobile-board-card"><button className={task.status === '已完成' ? 'mobile-check complete' : 'mobile-check'} onClick={() => onComplete(task)} aria-label="完成任务">{task.status === '已完成' && <Check size={12} strokeWidth={3} />}</button><button className="mobile-board-main" onClick={() => onOpen(task)}><strong>{task.title}</strong><footer>{project && <span><i style={{ background: project.color || '#8592a6' }} />{project.name}</span>}{due && <time className={due < today() ? 'overdue' : ''}>{due === today() ? '今天' : due < today() ? '逾期' : due.slice(5).replace('-', '/')}</time>}</footer></button>{(task.importance || task.urgency) && <i className={`mobile-priority ${task.importance && task.urgency ? 'both' : task.importance ? 'important' : 'urgent'}`} />}</article>; }
function MobileExploreHub({ onChoose }) { return <section className="mobile-explore-hub"><p>在这里按时间、优先级或历史记录查看任务。</p><div><button onClick={() => onChoose('calendar')}><CalendarDays size={18} /><span><strong>日历</strong><small>按日期安排任务</small></span><ChevronRight size={16} /></button><button onClick={() => onChoose('quadrant')}><Grid2X2 size={18} /><span><strong>四象限</strong><small>按轻重缓急排序</small></span><ChevronRight size={16} /></button><button onClick={() => onChoose('review')}><Clock3 size={18} /><span><strong>本周回顾</strong><small>查看完成与待处理</small></span><ChevronRight size={16} /></button><button onClick={() => onChoose('archive')}><Archive size={18} /><span><strong>归档</strong><small>已完成与已取消</small></span><ChevronRight size={16} /></button><button onClick={() => onChoose('manage')}><Folder size={18} /><span><strong>项目与分类</strong><small>维护你的任务树</small></span><ChevronRight size={16} /></button></div></section>; }
function MobileProjectManager({ projects, categories, onCreateProject, onCreateCategory, onRenameProject, onRenameCategory }) { const [newProject, setNewProject] = useState(''); const [newCategoryFor, setNewCategoryFor] = useState(''); const [newCategory, setNewCategory] = useState(''); const [editing, setEditing] = useState(null); const [name, setName] = useState(''); const saveProject = async (event) => { event.preventDefault(); if (await onCreateProject(newProject)) setNewProject(''); }; const saveCategory = async (event) => { event.preventDefault(); if (newCategoryFor && await onCreateCategory(newCategory, newCategoryFor)) { setNewCategory(''); setNewCategoryFor(''); } }; const beginEdit = (kind, item) => { setEditing(`${kind}:${item.id}`); setName(item.name); }; const saveEdit = async (kind, item) => { const saved = kind === 'project' ? await onRenameProject(item.id, name) : await onRenameCategory(item.id, name); if (saved) setEditing(null); }; return <section className="mobile-project-manager"><p className="mobile-intro">项目和分类是一棵树；可在这里直接新增或改名。</p><form className="mobile-inline-form" onSubmit={saveProject}><input value={newProject} onChange={(event) => setNewProject(event.target.value)} placeholder="新建项目名称" /><button disabled={!newProject.trim()}>新增项目</button></form>{projects.map((project) => <article key={project.id} className="mobile-project-node"><header><i style={{ background: project.color || '#5f7eea' }} />{editing === `project:${project.id}` ? <form onSubmit={(event) => { event.preventDefault(); saveEdit('project', project); }}><input value={name} onChange={(event) => setName(event.target.value)} /><button>保存</button></form> : <><strong>{project.name}</strong><button onClick={() => beginEdit('project', project)}>改名</button></>}</header>{categories.filter((item) => item.project_id === project.id).map((category) => <div className="mobile-category-node" key={category.id}>{editing === `category:${category.id}` ? <form onSubmit={(event) => { event.preventDefault(); saveEdit('category', category); }}><input value={name} onChange={(event) => setName(event.target.value)} /><button>保存</button></form> : <><span>#{category.name}</span><button onClick={() => beginEdit('category', category)}>改名</button></>}</div>)}{newCategoryFor === project.id ? <form className="mobile-inline-form category-form" onSubmit={saveCategory}><input value={newCategory} onChange={(event) => setNewCategory(event.target.value)} placeholder="分类名称" /><button disabled={!newCategory.trim()}>创建</button><button type="button" onClick={() => setNewCategoryFor('')}>取消</button></form> : <button className="mobile-add-category" onClick={() => setNewCategoryFor(project.id)}><Plus size={14} />新增分类</button>}</article>)}</section>; }
function MobileFilters({ filter, setFilter, projects, categories }) { const patch = (key, value) => setFilter((current) => ({ ...current, [key]: current[key] === value ? '' : value })); return <section className="mobile-filters"><header><strong>筛选条件</strong><button onClick={() => setFilter({ priority: '', status: '', project: '', category: '' })}>清除</button></header><MobileFilterLine label="状态" values={[['收件箱', '收集箱'], ['待进行', '待办'], ['进行中', '进行中'], ['阻塞', '已阻塞']]} selected={filter.status} onPick={(value) => patch('status', value)} /><MobileFilterLine label="优先级" values={[['important', '重要'], ['urgent', '紧急']]} selected={filter.priority} onPick={(value) => patch('priority', value)} />{projects.length > 0 && <MobileFilterLine label="项目" values={projects.map((item) => [item.id, item.name])} selected={filter.project} onPick={(value) => patch('project', value)} />}{categories.length > 0 && <MobileFilterLine label="分类" values={categories.map((item) => [item.id, item.name])} selected={filter.category} onPick={(value) => patch('category', value)} />}</section>; }
function MobileFilterLine({ label, values, selected, onPick }) { return <div className="mobile-filter-line"><span>{label}</span><div>{values.map(([value, name]) => <button key={value} className={selected === value ? 'selected' : ''} onClick={() => onPick(value)}>{name}</button>)}</div></div>; }
function MobileCalendar({ tasks, projects, onOpen }) { const [month, setMonth] = useState(new Date()); const [day, setDay] = useState(today()); const marked = tasks.reduce((result, task) => { const key = task.scheduled_for || dateOnly(task.due_at); if (key) result[key] = [...(result[key] || []), task]; return result; }, {}); const eventDays = Object.keys(marked).map((key) => new Date(`${key}T12:00:00`)); const entries = marked[day] || []; return <section className="mobile-calendar"><DayPicker mode="single" month={month} onMonthChange={setMonth} selected={new Date(`${day}T12:00:00`)} onDayClick={(value) => setDay(dateOnly(value.toISOString()))} modifiers={{ event: eventDays }} modifiersClassNames={{ event: 'mobile-calendar-event' }} /><header><strong>{day === today() ? '今天的安排' : day}</strong><small>{entries.length} 项</small></header>{entries.length ? entries.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} />) : <p className="mobile-section-empty">这一天没有已安排的任务</p>}</section>; }
function MobileQuadrants({ tasks, projects, childrenByParent, onOpen }) { const definitions = [{ key: 'iu', title: '重要且紧急', test: (task) => task.importance && task.urgency }, { key: 'in', title: '重要不紧急', test: (task) => task.importance && !task.urgency }, { key: 'nu', title: '紧急不重要', test: (task) => !task.importance && task.urgency }, { key: 'nn', title: '暂不重要', test: (task) => !task.importance && !task.urgency }]; return <section className="mobile-quadrants"><div className="mobile-quad-axis"><span>重要</span><span>紧急 →</span></div><div className="mobile-quad-grid">{definitions.map((definition) => { const entries = tasks.filter(definition.test); return <article key={definition.key} className={`mobile-quad-cell ${definition.key}`}><header><strong>{definition.title}</strong><small>{entries.length}</small></header>{entries.length ? entries.map((task) => <button key={task.id} onClick={() => onOpen(task)}><i className={(childrenByParent.get(task.id) || []).length ? 'parent' : ''} />{task.title}</button>) : <span>暂无任务</span>}</article>; })}</div><p>横轴：不紧急 → 紧急；纵轴：不重要 → 重要。</p></section>; }
function MobileReview({ tasks, projects, onOpen }) { const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - 6); const completed = tasks.filter((task) => task.status === '已完成' && task.updated_at && new Date(task.updated_at) >= cutoff); const activeCount = tasks.filter(active).length; return <section className="mobile-review"><div className="mobile-review-metrics"><article><span>本周完成</span><strong>{completed.length}</strong></article><article><span>仍待处理</span><strong>{activeCount}</strong></article></div><h2>本周完成的任务</h2>{completed.length ? completed.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} />) : <p className="mobile-section-empty">本周还没有完成记录</p>}</section>; }
function MobileArchive({ tasks, projects, onOpen, onComplete }) { return <section className="mobile-archive"><p className="mobile-intro">已完成和已取消的任务保留在这里，便于回顾。</p>{tasks.length ? tasks.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} onComplete={onComplete} />) : <p className="mobile-section-empty">没有归档任务</p>}</section>; }

function MobileTaskSection({ title, hint, tasks, projects, onOpen, onComplete, empty = '暂无任务' }) { return <section className="mobile-task-section"><header><div><strong>{title}</strong><small>{hint}</small></div>{tasks.length > 0 && <span>{tasks.length}</span>}</header>{tasks.length ? <div className="mobile-list">{tasks.map((task) => <MobileTaskRow key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} onOpen={onOpen} onComplete={onComplete} />)}</div> : <p className="mobile-section-empty">{empty}</p>}</section>; }

function MobileTaskRow({ task, project, onOpen, onComplete }) { const due = dateOnly(task.due_at); return <article className="mobile-task-row"><button className={task.status === '已完成' ? 'mobile-check complete' : 'mobile-check'} onClick={(event) => { event.stopPropagation(); onComplete?.(task); }} aria-label={task.status === '已完成' ? '恢复任务' : '完成任务'}>{task.status === '已完成' && <Check size={13} strokeWidth={3} />}</button><button className="mobile-task-main" onClick={() => onOpen(task)}><strong>{task.title}</strong><span>{project?.name || displayStatus(task.status)}{due && ` · ${due === today() ? '今天' : due < today() ? '已逾期' : due.slice(5).replace('-', '/')}`}</span></button>{(task.importance || task.urgency) && <i className={`mobile-priority ${task.importance && task.urgency ? 'both' : task.importance ? 'important' : 'urgent'}`} />}</article>; }

function MobileTaskForm({ parentTask, projects, categories, onBack, onCreate }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [status, setStatus] = useState(parentTask ? '待进行' : '收件箱'); const [projectId, setProjectId] = useState(parentTask?.project_id || ''); const [categoryId, setCategoryId] = useState(parentTask?.category_id || ''); const [priority, setPriority] = useState('normal'); const [scheduledFor, setScheduledFor] = useState(''); const [dueAt, setDueAt] = useState('');
  const submit = (event) => { event.preventDefault(); if (!title.trim()) return; onCreate({ title, description, parentId: parentTask?.id || null, projectId: projectId || null, categoryId: categoryId || null, status, importance: priority.includes('important'), urgency: priority.includes('urgent'), scheduledFor: scheduledFor || null, dueAt: dueAt ? `${dueAt}T09:00` : null }); };
  const chooseProject = (id) => { setProjectId(id); setCategoryId(''); };
  const scopedCategories = categories.filter((item) => item.project_id === projectId);
  return <section className="mobile-page mobile-form-page"><MobilePageHead title={parentTask ? '新建子任务' : '新建任务'} onBack={onBack} action={<button className="mobile-text-action" form="mobile-create-form" type="submit" disabled={!title.trim()}>创建</button>} /><form id="mobile-create-form" onSubmit={submit}><div className="mobile-editor-card"><input className="mobile-title-input" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="要做什么？" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="添加说明（可选）" rows="4" /></div>{parentTask && <p className="mobile-parent-note">父任务：{parentTask.title}</p>}<MobileField label="状态"><MobileChoice options={STATUS_COLUMNS.map((item) => ({ value: item.key, label: item.label }))} value={status} onChange={setStatus} /></MobileField><MobileField label="归属项目"><div className="mobile-pills"><button type="button" className={!projectId ? 'selected' : ''} onClick={() => chooseProject('')}>收集箱</button>{projects.map((project) => <button type="button" key={project.id} className={projectId === project.id ? 'selected' : ''} onClick={() => chooseProject(project.id)}>{project.name}</button>)}</div></MobileField>{scopedCategories.length > 0 && <MobileField label="分类"><div className="mobile-pills">{scopedCategories.map((category) => <button type="button" key={category.id} className={categoryId === category.id ? 'selected' : ''} onClick={() => setCategoryId(categoryId === category.id ? '' : category.id)}>{category.name}</button>)}</div></MobileField>}<MobileField label="优先级"><MobileChoice value={priority} onChange={setPriority} options={[{ value: 'normal', label: '普通' }, { value: 'important', label: '重要' }, { value: 'urgent', label: '紧急' }, { value: 'important-urgent', label: '重要且紧急' }]} /></MobileField><MobileField label="计划日期"><input className="mobile-date-input" type="date" value={scheduledFor} onChange={(event) => setScheduledFor(event.target.value)} /></MobileField><MobileField label="截止日期"><input className="mobile-date-input" type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /></MobileField></form></section>;
}

function MobileTaskDetail({ task, projects, categories, childTasks, onBack, onSave, onDelete, onOpen, onAddChild }) {
  const [draft, setDraft] = useState(() => ({ ...task, due_at: dateOnly(task.due_at) })); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const revision = useRef(0);
  useEffect(() => { setDraft({ ...task, due_at: dateOnly(task.due_at) }); setDirty(false); }, [task]);
  const set = (key, value) => { revision.current += 1; setDirty(true); setDraft((current) => ({ ...current, [key]: value })); };
  useEffect(() => { if (!dirty) return undefined; const timer = window.setTimeout(async () => { const currentRevision = revision.current; setSaving(true); const saved = await onSave(task.id, { title: draft.title.trim() || task.title, description: draft.description || '', status: draft.status, importance: draft.importance, urgency: draft.urgency, project_id: draft.project_id || null, category_id: draft.category_id || null, scheduled_for: draft.scheduled_for || null, due_at: draft.due_at ? new Date(`${draft.due_at}T09:00:00+08:00`).toISOString() : null }, ''); if (saved && currentRevision === revision.current) setDirty(false); setSaving(false); }, 550); return () => window.clearTimeout(timer); }, [dirty, draft, onSave, task.id, task.title]);
  const priority = draft.importance && draft.urgency ? 'important-urgent' : draft.importance ? 'important' : draft.urgency ? 'urgent' : 'normal';
  const scopedCategories = categories.filter((item) => item.project_id === draft.project_id);
  const chooseProject = (id) => { set('project_id', id); set('category_id', ''); };
  return <section className="mobile-page mobile-detail-page"><MobilePageHead title="任务详情" onBack={onBack} action={<button className="mobile-delete" onClick={() => onDelete(task)}>删除</button>} /><div className="mobile-save-state">{saving || dirty ? '正在保存…' : '已自动保存'}</div><div className="mobile-editor-card"><input className="mobile-title-input" value={draft.title || ''} onChange={(event) => set('title', event.target.value)} /><textarea value={draft.description || ''} onChange={(event) => set('description', event.target.value)} placeholder="添加说明、想法或下一步…" rows="5" /></div><MobileField label="状态"><MobileChoice options={STATUS_COLUMNS.map((item) => ({ value: item.key, label: item.label }))} value={draft.status} onChange={(value) => set('status', value)} /></MobileField><MobileField label="归属项目"><div className="mobile-pills"><button className={!draft.project_id ? 'selected' : ''} onClick={() => chooseProject('')}>收集箱</button>{projects.map((project) => <button key={project.id} className={draft.project_id === project.id ? 'selected' : ''} onClick={() => chooseProject(project.id)}>{project.name}</button>)}</div></MobileField>{scopedCategories.length > 0 && <MobileField label="分类"><div className="mobile-pills">{scopedCategories.map((category) => <button key={category.id} className={draft.category_id === category.id ? 'selected' : ''} onClick={() => set('category_id', draft.category_id === category.id ? '' : category.id)}>{category.name}</button>)}</div></MobileField>}<MobileField label="优先级"><MobileChoice value={priority} onChange={(value) => { set('importance', ['important', 'important-urgent'].includes(value)); set('urgency', ['urgent', 'important-urgent'].includes(value)); }} options={[{ value: 'normal', label: '普通' }, { value: 'important', label: '重要' }, { value: 'urgent', label: '紧急' }, { value: 'important-urgent', label: '重要且紧急' }]} /></MobileField><MobileField label="计划日期"><input className="mobile-date-input" type="date" value={draft.scheduled_for || ''} onChange={(event) => set('scheduled_for', event.target.value)} /></MobileField><MobileField label="截止日期"><input className="mobile-date-input" type="date" value={draft.due_at || ''} onChange={(event) => set('due_at', event.target.value)} /></MobileField><section className="mobile-children"><header><strong>子任务</strong><span>{childTasks.filter((item) => item.status === '已完成').length}/{childTasks.length}</span><button onClick={onAddChild}><Plus size={15} />添加</button></header>{childTasks.map((child) => <button key={child.id} onClick={() => onOpen(child)}><span className={child.status === '已完成' ? 'child-check done' : 'child-check'}>{child.status === '已完成' && <Check size={10} />}</span>{child.title}<ChevronRight size={15} /></button>)}</section></section>;
}

function MobilePageHead({ title, onBack, action }) { return <header className="mobile-page-head"><button onClick={onBack} aria-label="返回"><ChevronLeft size={23} /></button><strong>{title}</strong>{action || <span />}</header>; }
function MobileField({ label, children }) { return <section className="mobile-field"><h2>{label}</h2>{children}</section>; }
function MobileChoice({ options, value, onChange }) { return <div className="mobile-choice">{options.map((option) => <button type="button" key={option.value} className={value === option.value ? 'selected' : ''} onClick={() => onChange(option.value)}>{option.label}</button>)}</div>; }

function NavButton({ icon: Glyph, label, active, onClick, count }) { return <button className={active ? 'active' : ''} onClick={onClick}><Glyph size={16} /><span>{label}</span>{count !== undefined && <small>{count}</small>}</button>; }
function InlineName({ placeholder, onCancel, onSubmit }) { const [name, setName] = useState(''); return <form className="inline-name" onSubmit={(event) => { event.preventDefault(); onSubmit(name); }}><input autoFocus value={name} placeholder={placeholder} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') onCancel(); }} /><button type="button" onClick={onCancel}><X size={13} /></button></form>; }
function InlineRename({ initialValue, onCancel, onSubmit }) { const [name, setName] = useState(initialValue); return <form className="inline-name tree-rename" onSubmit={(event) => { event.preventDefault(); onSubmit(name); }}><input autoFocus value={name} aria-label="重命名" onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') onCancel(); }} /><button type="button" onClick={onCancel}><X size={13} /></button></form>; }
function InlineCategory({ projects, projectId, onCancel, onSubmit }) { const [name, setName] = useState(''); const [project, setProject] = useState(projectId || projects[0]?.id || ''); return <form className="inline-category" onSubmit={(event) => { event.preventDefault(); onSubmit(name, project); }}><input autoFocus value={name} placeholder="分类名称" onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') onCancel(); }} /><UiSelect value={project} onValueChange={setProject} placeholder="选择项目" options={projects.map((item) => ({ value: item.id, label: item.name }))} /><button type="button" onClick={onCancel}><X size={13} /></button></form>; }

function QuickCreate({ projectId, status, projects, onCancel, onSubmit }) { const [title, setTitle] = useState(''); const [project, setProject] = useState(projectId || ''); return <form className="quick-create" onSubmit={(event) => { event.preventDefault(); onSubmit(title, project || null); }}><Plus size={18} /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={`新增${displayStatus(status)}任务，按回车键保存`} /><UiSelect value={project} onValueChange={setProject} placeholder="收件箱" options={[{ value: '', label: '收件箱' }, ...projects.map((item) => ({ value: item.id, label: item.name }))]} /><button type="button" className="icon-button" onClick={onCancel}><X size={16} /></button><button className="primary" type="submit">添加</button></form>; }
function CreateTaskSheet({ open, initialStatus, projectId, parentTask, projects, onOpenChange, onSubmit }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [project, setProject] = useState(projectId || ''); const [status, setStatus] = useState(initialStatus || '收件箱'); const [priority, setPriority] = useState('normal'); const [scheduledFor, setScheduledFor] = useState(null); const [dueAt, setDueAt] = useState(null); const [detailsOpen, setDetailsOpen] = useState(false);
  useEffect(() => { if (open) { setProject(projectId || parentTask?.project_id || ''); setStatus(initialStatus || '收件箱'); setTitle(''); setDescription(''); setPriority('normal'); setScheduledFor(null); setDueAt(null); setDetailsOpen(Boolean(parentTask)); } }, [open, initialStatus, projectId, parentTask]);
  const create = async (event) => { event.preventDefault(); const task = await onSubmit({ title, description, projectId: project || null, parentId: parentTask?.id || null, status, importance: priority.includes('important'), urgency: priority.includes('urgent'), scheduledFor, dueAt }); if (task) onOpenChange(false); };
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="task-overlay" /><Dialog.Content className="create-task-sheet" aria-describedby={undefined}><div className="sheet-top"><span>{parentTask ? '新建子任务' : '新建任务'}</span><Dialog.Close className="icon-button" aria-label="关闭"><X size={17} /></Dialog.Close></div><Dialog.Title className="sr-only">{parentTask ? '新建子任务' : '新建任务'}</Dialog.Title><form onSubmit={create}>{parentTask && <div className="parent-task-note"><span>父任务</span><strong>{parentTask.title}</strong></div>}<label className="create-title"><span>先写下要做什么</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例如：整理周会纪要" /></label><Collapsible.Root open={detailsOpen} onOpenChange={setDetailsOpen} className="create-details"><Collapsible.Trigger type="button" className="create-expand"><Plus size={14} />{detailsOpen ? '收起补充信息' : '补充说明、项目、优先级或时间'}</Collapsible.Trigger><Collapsible.Content className="create-details-content"><label className="create-description"><span>说明</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="补充背景、下一步或备注…" rows="3" /></label><div className="create-field"><span>状态</span><StatusSwitch value={status} onValueChange={setStatus} /></div><div className="create-field"><span>归属项目</span><UiSelect value={project} onValueChange={setProject} placeholder="收件箱" options={[{ value: '', label: '收件箱' }, ...projects.map((item) => ({ value: item.id, label: item.name }))]} /></div><div className="create-field create-priority"><span>优先级</span><PriorityRadio value={priority} onValueChange={setPriority} /></div><div className="create-dates"><DatePickerField label="计划日期" value={scheduledFor} onValueChange={setScheduledFor} /><DatePickerField label="截止时间" value={dueAt} onChange={setDueAt} includeTime /></div></Collapsible.Content></Collapsible.Root><div className="create-actions"><Dialog.Close className="secondary" type="button">取消</Dialog.Close><button className="primary" type="submit" disabled={!title.trim()}>创建任务</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function FilterMenu({ filters, setFilters, projects, categories, onClear, onClose }) {
  const patch = (key, value) => setFilters((current) => ({ ...current, [key]: value }));
  return <Popover.Root open onOpenChange={(open) => !open && onClose()}><Popover.Anchor asChild><span className="filter-anchor" /></Popover.Anchor><Popover.Portal><Popover.Content className="filter-menu" sideOffset={8} align="end" onOpenAutoFocus={(event) => event.preventDefault()}><div className="filter-menu-head"><strong>筛选任务</strong><button onClick={onClear}>清除</button></div><FilterSelect label="状态" value={filters.status} onChange={(value) => patch('status', value)} options={[{ value: '', label: '全部状态' }, ...STATUS_COLUMNS.map((item) => ({ value: item.key, label: item.label }))]} /><FilterSelect label="优先级" value={filters.priority} onChange={(value) => patch('priority', value)} options={[{ value: '', label: '不限' }, { value: 'important', label: '重要' }, { value: 'urgent', label: '紧急' }]} /><FilterSelect label="日期" value={filters.date} onChange={(value) => patch('date', value)} options={[{ value: '', label: '不限' }, { value: 'overdue', label: '已逾期' }, { value: 'today', label: '今天' }]} /><FilterSelect label="项目" value={filters.project} onChange={(value) => patch('project', value)} options={[{ value: '', label: '全部项目' }, ...projects.map((item) => ({ value: item.id, label: item.name }))]} /><FilterSelect label="标签 / 分类" value={filters.category} onChange={(value) => patch('category', value)} options={[{ value: '', label: '全部分类' }, ...categories.map((item) => ({ value: item.id, label: item.name }))]} /><button className="filter-done" onClick={onClose}>完成</button></Popover.Content></Popover.Portal></Popover.Root>;
}
function FilterSelect({ label, value, onChange, options }) { return <div className="filter-select"><span>{label}</span><UiSelect value={value} onValueChange={onChange} placeholder="不限" options={options} /></div>; }
function UiSelect({ value, onValueChange, placeholder, options, className = '' }) { return <Select.Root value={value || undefined} onValueChange={(next) => onValueChange(next === '__empty' ? '' : next)}><Select.Trigger className={`ui-select ${className}`}><Select.Value placeholder={placeholder} /><ChevronDown size={14} /></Select.Trigger><Select.Portal><Select.Content className="ui-select-content" position="popper" sideOffset={5}><Select.Viewport>{options.map((option) => <Select.Item className="ui-select-item" key={option.value || '__empty'} value={option.value || '__empty'}><Select.ItemText>{option.label}</Select.ItemText><Select.ItemIndicator><Check size={13} /></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>; }
function ViewSwitch({ mode, setMode }) { return <div className="view-switch"><button className={mode === 'board' ? 'selected' : ''} onClick={() => setMode('board')}><Columns3 size={15} />看板</button><button className={mode === 'list' ? 'selected' : ''} onClick={() => setMode('list')}><List size={15} />列表</button></div>; }

function ViewContent({ view, mode, tasks, month, setMonth, onSelect, onComplete, onUpdate, onDelete, onCreate, childrenByParent, projects, categories, onQuickCreate }) {
  const root = tasks.filter((task) => !task.parent_id);
  if (view === 'inbox') return <InboxWorkspace tasks={root.filter((task) => active(task) && task.status === '收件箱')} projects={projects} categories={categories} onSelect={onSelect} onComplete={onComplete} onSave={onUpdate} onDelete={onDelete} onAddChild={(task) => onQuickCreate('待进行', task)} childrenByParent={childrenByParent} />;
  if (view === 'archive') return <TaskList tasks={root.filter((task) => task.archived_at || ['已完成', '已取消'].includes(task.status))} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} childrenByParent={childrenByParent} projects={projects} categories={categories} empty="还没有归档记录" />;
  if (view === 'quadrant') return <Quadrants tasks={root.filter((task) => active(task) && task.status !== '阻塞')} onSelect={onSelect} childrenByParent={childrenByParent} />;
  if (view === 'calendar') return <Calendar tasks={root.filter(active)} month={month} setMonth={setMonth} onSelect={onSelect} />;
  if (view === 'review') return <WeeklyReview tasks={root} projects={projects} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} childrenByParent={childrenByParent} categories={categories} />;
  if (view === 'status' || view === 'project') return mode === 'board' ? <StatusBoard tasks={root} projects={projects} categories={categories} childrenByParent={childrenByParent} onSelect={onSelect} onUpdate={onUpdate} onQuickCreate={onQuickCreate} /> : <StatusList tasks={root} projects={projects} categories={categories} childrenByParent={childrenByParent} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} />;
  const date = today(); const working = root.filter((task) => active(task) && task.status !== '阻塞');
  const important = working.filter((task) => task.importance || task.urgency);
  const remaining = working.filter((task) => !important.includes(task));
  const dueNow = remaining.filter((task) => task.due_at && dateOnly(task.due_at) <= date || task.scheduled_for === date);
  const inProgress = remaining.filter((task) => task.status === '进行中' && !dueNow.includes(task));
  const inbox = remaining.filter((task) => task.status === '收件箱' || (!task.due_at && !task.scheduled_for && task.status !== '进行中'));
  return <ActionWorkspace important={important} dueNow={dueNow} inProgress={inProgress} inbox={inbox} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} onCreate={onCreate} onOpenCreate={() => onQuickCreate('收件箱')} childrenByParent={childrenByParent} projects={projects} categories={categories} />;
}
function ActionWorkspace({ important, dueNow, inProgress, inbox, onCreate, onOpenCreate, ...props }) { const groups = [{ title: '优先处理', hint: '手动标记的重要或紧急任务', tasks: important.slice(0, 5), tone: 'attention' }, { title: '今天要做', hint: '今天计划或已到截止日期', tasks: dueNow, tone: 'plan' }, { title: '正在推进', hint: '已经开始的任务', tasks: inProgress, tone: 'progress' }, { title: '待处理', hint: '收件箱与未安排任务', tasks: inbox, tone: 'neutral' }]; return <div className="action-workspace"><CaptureBar onCreate={onCreate} onOpenCreate={onOpenCreate} /><div className="action-summary">{groups.slice(0, 3).map((group) => <div key={group.title} className={`action-metric ${group.tone}`}><span>{group.title}</span><strong>{group.tasks.length}</strong></div>)}</div>{groups.map((group) => <section key={group.title} className={`action-section ${group.tone}`}><header><div><strong>{group.title}</strong><span>{group.hint}</span></div><small>{group.tasks.length}</small></header><TaskList tasks={group.tasks} {...props} empty="暂无任务" /></section>)}</div>; }
function CaptureBar({ onCreate, onOpenCreate }) { const [title, setTitle] = useState(''); const submit = async (event) => { event.preventDefault(); if (await onCreate({ title, status: '收件箱' })) setTitle(''); }; return <form className="capture-bar" onSubmit={submit}><Plus size={18} /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="快速记录一件要做的事" aria-label="快速记录任务" /><button type="button" className="secondary capture-more" onClick={onOpenCreate}>添加详情</button><button className="primary" type="submit" disabled={!title.trim()}>保存</button></form>; }
function WeeklyReview({ tasks, projects, ...props }) { const now = new Date(); const monday = new Date(now); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7)); monday.setHours(0, 0, 0, 0); const completed = tasks.filter((task) => task.completed_at && new Date(task.completed_at) >= monday); const added = tasks.filter((task) => new Date(task.created_at) >= monday && active(task)); const importantOpen = tasks.filter((task) => active(task) && (task.importance || task.urgency)); const byProject = completed.reduce((map, task) => { const key = task.project_id || 'inbox'; map.set(key, [...(map.get(key) || []), task]); return map; }, new Map()); return <div className="review-workspace"><div className="review-metrics"><div><span>本周完成</span><strong>{completed.length}</strong></div><div><span>本周新增未完成</span><strong>{added.length}</strong></div><div><span>重要未完成</span><strong>{importantOpen.length}</strong></div></div><section className="review-section"><header><strong>本周完成了什么</strong><span>按项目归类</span></header>{completed.length ? [...byProject.entries()].map(([projectId, items]) => <div className="review-project" key={projectId}><strong>{projects.find((project) => project.id === projectId)?.name || '收件箱'}</strong><TaskList tasks={items} {...props} projects={projects} /></div>) : <div className="empty">本周还没有完成的任务</div>}</section><section className="review-section"><header><strong>重要但未完成</strong><span>下周优先关注</span></header><TaskList tasks={importantOpen} {...props} projects={projects} empty="暂无重要未完成任务" /></section></div>; }
function Section({ title, tasks, ...props }) { return <section className="section"><div className="section-head"><h2>{title}</h2><span>{tasks.length} 项</span></div><TaskList tasks={tasks} {...props} /></section>; }
function TaskList({ tasks, onSelect, onComplete, onUpdate, childrenByParent, projects = [], categories = [], empty = '暂无任务', tree = false }) { return <div className={tree ? 'task-list task-tree' : 'task-list'}>{tasks.length ? tasks.map((task) => tree ? <TaskTreeNode key={task.id} task={task} depth={0} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} childrenByParent={childrenByParent} projects={projects} categories={categories} /> : <TaskRow key={task.id} task={task} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} children={childrenByParent.get(task.id) || []} project={projects.find((item) => item.id === task.project_id)} category={categories.find((item) => item.id === task.category_id)} />) : <div className="empty">{empty}</div>}</div>; }
function TaskTreeNode({ task, depth, onSelect, onComplete, onUpdate, childrenByParent, projects, categories }) { const children = childrenByParent.get(task.id) || []; const [open, setOpen] = useState(true); return <div className="tree-node" style={{ '--depth': depth }}><div className="tree-node-line">{children.length ? <button className="tree-toggle" aria-label={open ? '收起子任务' : '展开子任务'} onClick={() => setOpen((value) => !value)}><ChevronRight className={open ? 'open' : ''} size={14} /></button> : <span className="tree-spacer" />}<TaskRow task={task} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} children={children} project={projects.find((item) => item.id === task.project_id)} category={categories.find((item) => item.id === task.category_id)} /></div>{open && children.map((child) => <TaskTreeNode key={child.id} task={child} depth={depth + 1} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} childrenByParent={childrenByParent} projects={projects} categories={categories} />)}</div>; }
function TaskRow({ task, onSelect, onComplete, onUpdate, children, project, category }) {
  const due = dateOnly(task.due_at); const isLate = due && due < today();
  return <article className="task-row" tabIndex="0" onClick={() => onSelect(task)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(task); } }}><button className={task.status === '已完成' ? 'check done' : 'check'} aria-label={`${task.status === '已完成' ? '恢复' : '完成'}：${task.title}`} onClick={(event) => { event.stopPropagation(); onComplete(task); }}>{task.status === '已完成' && <Check size={12} strokeWidth={3} />}</button><div className="task-copy"><strong>{task.title}</strong><div className="task-meta"><span onClick={(event) => event.stopPropagation()}><StatusSwitch value={task.status} onValueChange={(status) => onUpdate(task.id, { status }, `已更新为${displayStatus(status)}`)} /></span>{project && <span className="row-project"><i style={{ background: project.color || '#8290aa' }} />{project.name}</span>}{category && <span className="row-category">#{category.name}</span>}{children.length > 0 && <span className="child-count"><Circle size={10} />{children.filter((item) => item.status === '已完成').length}/{children.length}</span>}</div></div><div className={isLate ? 'due overdue' : 'due'}>{isLate ? '已逾期' : due === today() ? '今天截止' : due ? `${due.slice(5).replace('-', '/')} 截止` : ''}</div></article>;
}

function StatusBoard({ tasks, projects, categories, childrenByParent, onSelect, onUpdate, onQuickCreate }) { return <div className="status-board">{STATUS_COLUMNS.map((column) => { const entries = tasks.filter((task) => task.status === column.key); return <section className={`board-column tone-${column.tone}`} key={column.key}><header><div><span className="status-dot" /><strong>{column.label}</strong><small>{entries.length}</small></div><button aria-label={`新建${column.label}任务`} onClick={() => onQuickCreate(column.key)}><Plus size={15} /></button></header><div className="board-cards">{entries.length ? entries.map((task) => <BoardCard key={task.id} task={task} project={projects.find((item) => item.id === task.project_id)} category={categories.find((item) => item.id === task.category_id)} children={childrenByParent.get(task.id) || []} onClick={() => onSelect(task)} onStatus={(status) => onUpdate(task.id, { status }, `已更新为${displayStatus(status)}`)} />) : <button className="board-empty" onClick={() => onQuickCreate(column.key)}>+ 添加任务</button>}</div></section>; })}</div>; }
function BoardCard({ task, project, category, children, onClick, onStatus }) { const due = dateOnly(task.due_at); return <article className="board-card" tabIndex="0" onClick={onClick} onKeyDown={(event) => { if (event.key === 'Enter') onClick(); }}><div className="board-card-head"><strong>{task.title}</strong><span onClick={(event) => event.stopPropagation()}><StatusSwitch value={task.status} onValueChange={onStatus} /></span></div><div className="card-meta">{project && <span><i style={{ background: project.color || '#8290aa' }} />{project.name}</span>}{category && <span>#{category.name}</span>}</div><footer>{children.length > 0 && <span className="card-children"><Circle size={10} />{children.length}</span>}{due && <time className={due < today() ? 'overdue' : ''}>{due < today() ? '逾期' : due === today() ? '今天' : due.slice(5).replace('-', '/')}</time>}</footer></article>; }
function StatusList({ tasks, projects, categories, childrenByParent, onSelect, onComplete, onUpdate }) { return <div className="status-list">{STATUS_COLUMNS.map((column) => { const entries = tasks.filter((task) => task.status === column.key); return <Collapsible.Root key={column.key} className="status-group" defaultOpen><Collapsible.Trigger className="status-summary"><ChevronRight size={15} /><span className={`status-dot tone-${column.tone}`} /><strong>{column.label}</strong><small>{entries.length}</small></Collapsible.Trigger><Collapsible.Content><TaskList tree tasks={entries} projects={projects} categories={categories} childrenByParent={childrenByParent} onSelect={onSelect} onComplete={onComplete} onUpdate={onUpdate} empty="暂无任务" /></Collapsible.Content></Collapsible.Root>; })}</div>; }

function InboxWorkspace({ tasks, projects, categories, childrenByParent, onSelect, onComplete, onSave, onDelete, onAddChild }) {
  const [focused, setFocused] = useState(() => tasks[0] || null);
  const [mobileDetailOpen, setMobileDetailOpen] = useState(false);
  useEffect(() => setFocused((current) => tasks.find((task) => task.id === current?.id) || tasks[0] || null), [tasks]);
  useEffect(() => { if (!focused) setMobileDetailOpen(false); }, [focused]);
  const openTask = (task) => { setFocused(task); setMobileDetailOpen(true); };
  return <div className={mobileDetailOpen ? 'inbox-workspace mobile-detail-open' : 'inbox-workspace'}><aside className="inbox-list"><header><strong>收件箱</strong><span>{tasks.length} 项待处理</span></header>{tasks.length ? tasks.map((task) => <button key={task.id} className={focused?.id === task.id ? 'inbox-item selected' : 'inbox-item'} onClick={() => openTask(task)}><span className="inbox-item-icon"><Inbox size={14} /></span><div><strong>{task.title}</strong><small>{projects.find((item) => item.id === task.project_id)?.name || '未分类'} · {displayStatus(task.status)}</small></div><ChevronRight className="inbox-item-arrow" size={16} /></button>) : <div className="empty">收件箱已经清空</div>}</aside><section className="inbox-preview"><header className="inbox-mobile-detail-head"><button onClick={() => setMobileDetailOpen(false)} aria-label="返回收件箱"><ChevronLeft size={19} />收件箱</button><strong>任务详情</strong><span /></header>{focused ? <TaskEditor key={focused.id} task={focused} projects={projects} categories={categories} childTasks={childrenByParent.get(focused.id) || []} onSave={onSave} onComplete={onComplete} onDelete={onDelete} onAddChild={() => onAddChild(focused)} autoSave inbox /> : <div className="inbox-empty"><Inbox size={28} /><strong>收件箱已经清空</strong><span>记录新任务后会出现在这里。</span></div>}</section></div>;
}
function InboxEditor({ task, projects, categories, childCount, onSave, onOpen, onComplete }) {
  const [draft, setDraft] = useState({ ...task }); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(true);
  const set = (key, value) => { setSaved(false); setDraft((current) => ({ ...current, [key]: value })); };
  useEffect(() => { if (saved) return undefined; const timer = window.setTimeout(async () => { setSaving(true); const payload = { title: draft.title.trim() || task.title, description: draft.description || '', status: draft.status, project_id: draft.project_id || null, category_id: draft.category_id || null }; const updated = await onSave(task.id, payload, ''); if (updated) { setDraft(updated); setSaved(true); } setSaving(false); }, 650); return () => window.clearTimeout(timer); }, [draft, onSave, saved, task.id, task.title]);
  return <><div className="preview-crumb"><Inbox size={14} />收件箱 / 待处理 <span className={saving ? 'saving-state saving' : 'saving-state'}>{saving ? '正在保存' : saved ? '已保存' : '等待保存'}</span></div><div className="preview-head editor"><div><StatusSwitch value={draft.status} onValueChange={(value) => set('status', value)} /><input className="inbox-title-input" value={draft.title || ''} onChange={(event) => set('title', event.target.value)} aria-label="任务标题" /><textarea className="inbox-description-input" value={draft.description || ''} onChange={(event) => set('description', event.target.value)} placeholder="添加说明、想法或下一步…" rows="6" /></div></div><div className="preview-properties editor-properties"><TreeSelect projects={projects} categories={categories} projectId={draft.project_id} categoryId={draft.category_id} onValueChange={({ projectId, categoryId }) => { setSaved(false); setDraft((current) => ({ ...current, project_id: projectId, category_id: categoryId })); }} /><span>子任务 <b>{childCount} 项</b></span></div><div className="preview-actions"><button className="primary" onClick={() => onComplete(task)}><Check size={15} />完成</button></div></>;
}

function Quadrants({ tasks, onSelect, childrenByParent }) {
  const definitions = [
    { key: 'important-urgent', title: '重要且紧急', match: (task) => task.importance && task.urgency },
    { key: 'important-later', title: '重要不紧急', match: (task) => task.importance && !task.urgency },
    { key: 'delegate', title: '紧急不重要', match: (task) => !task.importance && task.urgency },
    { key: 'later', title: '暂不重要', match: (task) => !task.importance && !task.urgency }
  ];
  const groups = new Map(definitions.map((item) => [item.key, tasks.filter(item.match)]));
  const data = definitions.flatMap((definition) => (groups.get(definition.key) || []).map((task, index) => ({ task, x: (task.urgency ? 75 : 25) + ((index % 5) - 2) * 7, y: (task.importance ? 75 : 25) + (Math.floor(index / 5) - 1) * 8, parent: (childrenByParent.get(task.id) || []).length > 0 })));
  return <><section className="quadrant-chart"><div className="quad-axis quad-axis-y">重要程度 ↑</div><div className="quad-axis quad-axis-x">不紧急 ← 紧急程度 →</div><div className="quad-label q-label-urgent">重要且紧急</div><div className="quad-label q-label-plan">重要但不紧急</div><div className="quad-label q-label-delegate">不重要但紧急</div><div className="quad-label q-label-later">不重要且不紧急</div><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 38, right: 42, bottom: 42, left: 42 }}><CartesianGrid stroke="#e8e8e5" strokeDasharray="0" /><ReferenceLine x={50} stroke="#aeb6c0" strokeWidth={1.4} /><ReferenceLine y={50} stroke="#aeb6c0" strokeWidth={1.4} /><XAxis type="number" dataKey="x" domain={[0, 100]} ticks={[0, 50, 100]} tickLine={false} tickFormatter={(value) => value === 0 ? '不紧急' : value === 100 ? '紧急' : ''} /><YAxis type="number" dataKey="y" domain={[0, 100]} ticks={[0, 50, 100]} tickLine={false} tickFormatter={(value) => value === 0 ? '不重要' : value === 100 ? '重要' : ''} /><Tooltip cursor={false} content={({ active: isActive, payload }) => isActive && payload?.[0] ? <div className="quad-tooltip">{payload[0].payload.task.title}</div> : null} /><Scatter data={data} shape={(props) => <TaskPoint {...props} onSelect={onSelect} />} /></ScatterChart></ResponsiveContainer></section><section className="quadrant-mobile-grid">{definitions.map((definition) => { const entries = groups.get(definition.key) || []; return <article className={`quadrant-mobile-cell ${definition.key}`} key={definition.key}><header><strong>{definition.title}</strong><small>{entries.length}</small></header>{entries.length ? entries.map((task) => <button className="quadrant-mobile-task" key={task.id} onClick={() => onSelect(task)}>{(childrenByParent.get(task.id) || []).length > 0 && <Circle className="quad-parent" size={12} />}<span>{task.title}</span></button>) : <span className="quadrant-mobile-empty">暂无任务</span>}</article>; })}</section></>;
}
function TaskPoint({ cx, cy, payload, onSelect }) { return <circle className={payload.parent ? 'chart-task-dot parent' : 'chart-task-dot'} cx={cx} cy={cy} r={payload.parent ? 8 : 6} onClick={() => onSelect(payload.task)} />; }
function Calendar({ tasks, month, setMonth, onSelect }) { const [selectedDay, setSelectedDay] = useState(today()); const marked = tasks.reduce((map, task) => { const key = task.scheduled_for || dateOnly(task.due_at); if (key) map[key] = [...(map[key] || []), task]; return map; }, {}); const eventDays = Object.keys(marked).map((key) => new Date(`${key}T00:00:00`)); const entries = marked[selectedDay] || []; return <section className="calendar-library"><DayPicker mode="single" month={month} selected={new Date(`${selectedDay}T00:00:00`)} onMonthChange={setMonth} onDayClick={(day) => setSelectedDay(dateOnly(day.toISOString()))} showOutsideDays modifiers={{ event: eventDays }} modifiersClassNames={{ event: 'day-with-task' }} components={{ DayButton: ({ day, modifiers, ...props }) => { const key = dateOnly(day.date.toISOString()); const count = (marked[key] || []).length; return <button {...props} className={modifiers.event ? 'rdp-day_button day-task-button' : 'rdp-day_button'}>{day.date.getDate()}{count > 0 && <span className="day-task-count">{count}</span>}</button>; } }} /><aside className="calendar-agenda"><h2>{selectedDay === today() ? '今天的任务' : `${selectedDay.slice(5).replace('-', '/')} 的任务`}</h2>{entries.length ? entries.map((task) => <button key={task.id} onClick={() => onSelect(task)}><span>{task.due_at ? localDateTimeValue(task.due_at).slice(11) : '计划'}</span>{task.title}</button>) : <p>这一天没有已安排的任务</p>}</aside></section>; }

function TaskSheet({ task, projects, categories, childTasks, onClose, onSave, onDelete, onAddChild, onOpenTask }) { return <Dialog.Root open={Boolean(task)} onOpenChange={(open) => !open && onClose()}>{task && <Dialog.Portal><Dialog.Overlay className="task-overlay" /><Dialog.Content className="task-sheet" aria-describedby={undefined}><div className="sheet-top"><span>任务详情</span><Dialog.Close className="icon-button" aria-label="关闭详情"><X size={17} /></Dialog.Close></div><Dialog.Title className="sr-only">编辑任务</Dialog.Title><TaskEditor key={task.id} task={task} projects={projects} categories={categories} childTasks={childTasks} onSave={onSave} onDelete={onDelete} onAddChild={onAddChild} onOpenTask={onOpenTask} autoSave /></Dialog.Content></Dialog.Portal>}</Dialog.Root>; }
function TaskEditor({ task, projects, categories, childTasks, onSave, onDelete, onAddChild, onOpenTask, autoSave = false, inbox = false }) {
  const [draft, setDraft] = useState({ ...task, due_at: localDateTimeValue(task.due_at) });
  const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const revision = useRef(0);
  const set = (key, value) => { revision.current += 1; setDirty(true); setDraft((item) => ({ ...item, [key]: value })); };
  const save = async () => { const savedRevision = revision.current; setSaving(true); const payload = { title: draft.title.trim() || task.title, status: draft.status, importance: draft.importance, urgency: draft.urgency, description: draft.description || '', scheduled_for: draft.scheduled_for || null, due_at: draft.due_at ? new Date(`${draft.due_at}:00+08:00`).toISOString() : null, project_id: draft.project_id || null, category_id: draft.category_id || null }; const updated = await onSave(task.id, payload, autoSave ? '' : '已保存'); if (updated && revision.current === savedRevision) { setDirty(false); setSaving(false); } };
  useEffect(() => { if (!autoSave || !dirty) return undefined; const timer = window.setTimeout(save, 650); return () => window.clearTimeout(timer); }, [autoSave, dirty, draft]);
  const priority = draft.importance && draft.urgency ? 'important-urgent' : draft.importance ? 'important' : draft.urgency ? 'urgent' : 'normal';
  return <div className={inbox ? 'detail inbox-detail' : 'detail'}>
    <div className="detail-heading"><input className="detail-title" aria-label="任务名称" value={draft.title || ''} onChange={(event) => set('title', event.target.value)} /><StatusSwitch value={draft.status} onValueChange={(value) => set('status', value)} /></div>
    <textarea className="detail-description" value={draft.description || ''} onChange={(event) => set('description', event.target.value)} placeholder="添加说明…" rows="4" />
    <section className="detail-section"><h3>归属</h3><TreeSelect projects={projects} categories={categories} projectId={draft.project_id} categoryId={draft.category_id} onValueChange={({ projectId, categoryId }) => { revision.current += 1; setDirty(true); setDraft((current) => ({ ...current, project_id: projectId, category_id: categoryId })); }} /></section>
    <section className="detail-section"><h3>时间</h3><div className="property-list"><DatePickerField label="计划日期" value={draft.scheduled_for || ''} onValueChange={(value) => set('scheduled_for', value)} /><DatePickerField label="截止时间" value={draft.due_at || ''} includeTime onValueChange={(value) => set('due_at', value)} /></div></section>
    <section className="detail-section"><h3>优先级</h3><PriorityRadio value={priority} onValueChange={(value) => { set('importance', ['important', 'important-urgent'].includes(value)); set('urgency', ['urgent', 'important-urgent'].includes(value)); }} /></section>
    <section className="detail-section children-section"><div className="children-head"><h3>子任务 <em>{childTasks.filter((item) => item.status === '已完成').length}/{childTasks.length}</em></h3><button onClick={onAddChild}><Plus size={14} />添加子任务</button></div>{childTasks.length ? childTasks.map((child) => <button className="child" key={child.id} onClick={() => onOpenTask?.(child)}><span className={child.status === '已完成' ? 'child-check done' : 'child-check'}>{child.status === '已完成' && <Check size={10} strokeWidth={3} />}</span>{child.title}<ChevronRight size={14} /></button>) : <p className="child-empty">拆成小步骤，会更容易推进。</p>}</section>
    <div className="detail-actions"><DeleteTaskButton task={task} onDelete={onDelete} />{!autoSave && <button className="primary" onClick={save}>{saving ? '保存中…' : '保存更改'}</button>}{autoSave && <span className="autosave-note">{saving ? '正在保存…' : dirty ? '正在保存…' : '已自动保存'}</span>}</div>
  </div>;
}
function StatusSwitch({ value, onValueChange }) { return <Popover.Root><Popover.Trigger asChild><button className={`status-badge status-${value} status-switch`}><span>{displayStatus(value)}</span><ChevronDown size={12} /></button></Popover.Trigger><Popover.Portal><Popover.Content className="status-menu" sideOffset={6} align="end">{STATUS_COLUMNS.map((item) => <button key={item.key} className={item.key === value ? 'selected' : ''} onClick={() => onValueChange(item.key)}><span className={`status-dot tone-${item.tone}`} />{item.label}{item.key === value && <Check size={13} />}</button>)}</Popover.Content></Popover.Portal></Popover.Root>; }
function PriorityRadio({ value, onValueChange }) { const choices = [{ value: 'normal', label: '普通' }, { value: 'important', label: '重要' }, { value: 'urgent', label: '紧急' }, { value: 'important-urgent', label: '重要且紧急' }]; return <RadioGroup.Root className="priority-radio" value={value} onValueChange={onValueChange}>{choices.map((choice) => <label key={choice.value}><RadioGroup.Item value={choice.value} aria-label={choice.label}><RadioGroup.Indicator className="priority-radio-indicator" /></RadioGroup.Item><span>{choice.label}</span></label>)}</RadioGroup.Root>; }
function DeleteTaskButton({ task, onDelete }) { return <AlertDialog.Root><AlertDialog.Trigger asChild><button className="danger-button">删除</button></AlertDialog.Trigger><AlertDialog.Portal><AlertDialog.Overlay className="task-overlay" /><AlertDialog.Content className="delete-dialog"><AlertDialog.Title>删除任务？</AlertDialog.Title><AlertDialog.Description>“{task.title}”及其子任务将被删除，此操作无法撤销。</AlertDialog.Description><div><AlertDialog.Cancel className="secondary">取消</AlertDialog.Cancel><AlertDialog.Action className="danger-button" onClick={() => onDelete(task)}>删除任务</AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>; }
function DatePickerField({ label, value, onValueChange, includeTime = false }) { const selected = value ? new Date(`${value.slice(0, 10)}T12:00:00`) : undefined; const time = includeTime && value ? value.slice(11, 16) : '09:00'; const commitDate = (date) => { const day = date.toLocaleDateString('en-CA'); onValueChange(includeTime ? `${day}T${time}` : day); }; const timeOptions = Array.from({ length: 24 }, (_, hour) => ['00', '30'].map((minute) => ({ value: `${String(hour).padStart(2, '0')}:${minute}`, label: `${String(hour).padStart(2, '0')}:${minute}` }))).flat(); return <div className="date-picker-field"><span>{label}</span><Popover.Root><Popover.Trigger asChild><button className="date-picker-trigger"><CalendarDays size={14} /><span>{value ? (includeTime ? value.replace('T', ' ') : value) : '选择日期'}</span></button></Popover.Trigger><Popover.Portal><Popover.Content className="date-picker-popover" sideOffset={6} align="end"><DayPicker mode="single" selected={selected} onSelect={(date) => date && commitDate(date)} /><div className="date-picker-time">{includeTime && <UiSelect value={time} onValueChange={(next) => onValueChange(value ? `${value.slice(0, 10)}T${next}` : `${today()}T${next}`)} placeholder="时间" options={timeOptions} />}</div></Popover.Content></Popover.Portal></Popover.Root></div>; }
function TreeSelect({ projects, categories, projectId, categoryId, onValueChange }) { const value = categoryId ? `category:${categoryId}` : projectId ? `project:${projectId}` : ''; const options = [{ value: '', label: '未设置归属' }, ...projects.flatMap((project) => [{ value: `project:${project.id}`, label: `项目 · ${project.name}` }, ...categories.filter((category) => category.project_id === project.id).map((category) => ({ value: `category:${category.id}`, label: `　分类 · ${category.name}` }))])]; return <div className="tree-select"><span><Folder size={14} />归属</span><UiSelect value={value} placeholder="选择项目或分类" options={options} onValueChange={(next) => { if (!next) return onValueChange({ projectId: null, categoryId: null }); const [kind, id] = next.split(':'); if (kind === 'project') onValueChange({ projectId: id, categoryId: null }); else { const category = categories.find((item) => item.id === id); onValueChange({ projectId: category?.project_id || null, categoryId: id }); } }} /></div>; }

createRoot(document.getElementById('root')).render(<App />);
